### ISSUE TITLE
make available via package installers (e.g. Homebrew)

### ISSUE THREAD

**Issue by vassudanagunta** [birchb1024/frangipanni#2]
This is a useful tool.  It would get orders of magnitude greater spread if made available for easy install as well as version updates using the primary package manager for OSes you want to target (e.g. Homebrew for macOS).

**Comment by vassudanagunta** [comment]
Though users can easily create command line aliases, might want the installer to create a standard alias that is a bit easier to remember and type than "frangipanni".  Just sayin ;)

**Comment by birchb1024** [comment]
I will ensure it's statically linked and easy to download. Probably not time available to do a .deb. 
Probably not funds to buy an Apple. Perhaps you could send me a PR?

**Comment by bradparks** [comment]
I haven't used it, but I think [travis-ci will build mac stuff](https://blog.travis-ci.com/oss-announcement#:~:text=This%20migration%20enables%20all%20accounts,under%20travis%2Dci.com.) and is free for opensource projects
